config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search" => "users#search"
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "search" => "searches#search"
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
  end

  get 'tagsearches/search', to: 'tagsearches#search'
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def get_group_image
    if group_image.attached?
      group_image
    else
      'no_image.jpg'
    end
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  has_many :users, through: :group_users, source: :user

  def include_user?(user)
    group_users.exists?(user_id: user.id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    GroupMailer.send_mail(@mail_title, @mail_content,group_users).deliver
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true do |f| %>

  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :group_image, class: "form-control-file", accept: "image/*" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>

<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>introduction</th>
      <th>menber</th>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.group_users.count + 1 %></td>
      <% if group.is_owned_by?(current_user) %>
        <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-success group_#{group.id}" %></td>
      <% end %>
      <td></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>

      <h2 class="mt-3">New Book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= link_to "ユーザー一覧", users_path %>｜<%= link_to "グループを作成する", new_group_path %>
      <%= render 'index', groups: @groups %>
    </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>New Group</h3>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Event Mail</h2>
    <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :mail_title,class:'form-control'%>
        </div>
    <div class="form-group">
        <%=f.label:content %>
        <%= f.text_area :mail_content,class:'form-control' %>
    </div>
    <div>
    <%= f.submit'送信', class: "btn btn-sm btn-success" %>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container d-flex flex-column align-items-center text-left">
  <div>
    <h3 class="mb-3">送信が完了しました</h3>
    <p class="mb-1">内容は以下の通りです。</p>
    <div>
      [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
    </div>
    <div>
      [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>

      <h2 class="mt-3">New Book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <%= link_to "ユーザー一覧", users_path %>｜<%= link_to "グループ一覧", groups_path %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Group</th>
            <th>Introduction</th>
            <th>Menbers</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: "50x50" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <li style="list-style:none;"><%= @group.owner.name %></li>
              <% @group.users.each do |user| %>
                <li style="list-style:none;"><%= user.name %></li>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
              <% else %>
                <% if @group.include_user?(current_user) %>
                  <%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-success" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to 'Notice an Event',group_new_mail_path(@group), class: "btn btn-sm btn-info" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>