config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    get "search" => "users#search"
    resource :relationships, only: [:create, :destroy]
  	get "followings" => "relationships#followings", as: "followings"
  	get "followers" => "relationships#followers", as: "followers"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "search" => "searches#search"
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
  end

  get 'tagsearches/search', to: 'tagsearches#search'
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_today_book_count
    self.books.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day).count
  end

  def get_yesterday_book_count
    self.books.where(created_at: Date.yesterday.beginning_of_day..Date.yesterday.end_of_day).count
  end

  def get_2days_ago_book_count
    four_days_ago_start = Date.today.beginning_of_day - 2.days
    four_days_ago_end = Date.today.end_of_day - 2.days

    self.books.where(created_at: four_days_ago_start..four_days_ago_end).count
  end

  def get_3days_ago_book_count
    four_days_ago_start = Date.today.beginning_of_day - 3.days
    four_days_ago_end = Date.today.end_of_day - 3.days

    self.books.where(created_at: four_days_ago_start..four_days_ago_end).count
  end

  def get_4days_ago_book_count
    four_days_ago_start = Date.today.beginning_of_day - 4.days
    four_days_ago_end = Date.today.end_of_day - 4.days

    self.books.where(created_at: four_days_ago_start..four_days_ago_end).count
  end

  def get_5days_ago_book_count
    four_days_ago_start = Date.today.beginning_of_day - 5.days
    four_days_ago_end = Date.today.end_of_day - 5.days

    self.books.where(created_at: four_days_ago_start..four_days_ago_end).count
  end

  def get_6days_ago_book_count
    four_days_ago_start = Date.today.beginning_of_day - 6.days
    four_days_ago_end = Date.today.end_of_day - 6.days

    self.books.where(created_at: four_days_ago_start..four_days_ago_end).count
  end



  def get_book_week_post_count
    past_week_start = Date.today.beginning_of_day - 6.days
    past_week_end = Date.today.end_of_day

    self.books.where(created_at: past_week_start..past_week_end).count
  end

  def get_book_last_week_post_count
    past_week_start = Date.today.beginning_of_day - 14.days
    past_week_end = Date.today.end_of_day - 7.days

    self.books.where(created_at: past_week_start..past_week_end).count
  end

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :read_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if current_user
      if @user.id == current_user.id
      else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "Please choose a date"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "Guest users cannot transition to the profile editing screen."
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>Follow : <%= user.followings.count %></td>
        <td>Follower : <%= user.followers.count %></td>
        <% if current_user != user %>
          <td>
            <%= render "relationships/btn", user: user, options: { class: ""} %>
          </td>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follow</th>
    <th>
      <%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>Follower</th>
    <th><%= link_to user.followers.count,user_followers_path(user) %></th>
  </tr>
</table>

<div class='container'>

  <% unless user.guest_user? %>
  <div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  </div>
  <% end %>
  <div class='row'><p></p></div>
  <div class='row'>
  <% if current_user != user %>
    <%= render "relationships/btn", user: user, options: { class: ""} %>
  <% end %>
  </div>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %>｜<%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
<p></p>
        <% unless @user.id == current_user.id %>
          <% if (current_user.following? @user) && (@user.following? current_user)  %>
            <% if @isRoom == true %>
              <%= link_to "チャットへ", room_path(@roomId), class: "btn btn-outline-primary" %>
            <% else %>
              <%= form_with(model: @room) do |f| %>
                <%= f.fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, value: @user.id %>
                <% end %>
                <%= f.submit "チャットを始める", class:"btn btn-outline-success"%>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

     <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索' %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
      <p></p>
      <h2>投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>昨日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.get_today_book_count %></td>
            <td><%= @user.get_yesterday_book_count %></td>
            <% if @user.get_yesterday_book_count == 0 %>
              <td>昨日の投稿なし</td>
            <% else %>
              <td>
                <%= ((@user.get_today_book_count.to_f  / @user.get_yesterday_book_count.to_f ).round(2)*100).to_i %>%
              </td>
            <% end %>
          </tr>
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
          <tr>
            <td><%= @user.get_book_week_post_count %></td>
            <td><%= @user.get_book_last_week_post_count %></td>
            <% if @user.get_book_last_week_post_count == 0 %>
              <td>先週の投稿なし</td>
            <% else %>
              <td>
                <%= ((@user.get_book_week_post_count.to_f  / @user.get_book_last_week_post_count.to_f ).round(2)*100).to_i %>%
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <h2>7日分の投稿数</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>6日前</th>
            <th>5日前</th>
            <th>4日前</th>
            <th>3日前</th>
            <th>2日前</th>
            <th>1日前</th>
            <th>本日</th>
          </tr>
        </thead>
        <tbody>
            <td><%= @user.get_6days_ago_book_count %></td>
            <td><%= @user.get_5days_ago_book_count %></td>
            <td><%= @user.get_4days_ago_book_count %></td>
            <td><%= @user.get_3days_ago_book_count %></td>
            <td><%= @user.get_2days_ago_book_count %></td>
            <td><%= @user.get_yesterday_book_count %></td>
            <td><%= @user.get_today_book_count %></td>
        </tbody>
      </table>
        <canvas id="myChart"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
        var ctx = document.getElementById('myChart');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前' , '本日'],
                datasets: [{
            label: '投稿した本の数',
            data: [
              <%= @user.get_6days_ago_book_count %>,
              <%= @user.get_5days_ago_book_count %>,
              <%= @user.get_4days_ago_book_count %>,
              <%= @user.get_3days_ago_book_count %>,
              <%= @user.get_2days_ago_book_count %>,
              <%= @user.get_yesterday_book_count %>,
              <%= @user.get_today_book_count %>
              ],
            fill: false,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1
                }]
            },
            options: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            }
        });
        </script>
    </div>
  </div>
</div>